### PR TITLE
use jessie instead of stretch for tools build/deploy

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by djmitche** [comment]
For my own runs of tc-builder, this (jessie) works all the time, and stretch does not.

**Comment by owlishDeveloper** [comment]
I'm not sure what to say here. I tried all 4 variants (2 flavors of node and 2 flavors of nginx) - the only one that works for me is a stretch nginx on a stretch node image. (I am sure which images are which because I state the debian version explicitly, and when the build fails, I can see the non-tagged image that is left on my disk - its size corresponds to the size of the node image I was using)(I also confirm that my explicit debian versioning for node images works by running the image and looking at its `etc/os-release`)(I also noticed you must restart Docker after switching to a different node image, otherwise it hangs at`yarn` stage)

My suspicion is, both node and nginx must use the same debian. Which flavor works might depend, I think, on either the host OS, or Docker version, or the position of the stars in Sagittarius at your particular geographical location. We can arrange for a possibility of giving the debian version as a parameter (like, `./taskcluster-builder build --base-dir /tmp/base-dir --debian stretch`) <--- which could also be a longer term fix for this? Because new versions come out all the time, we can't hard code them?

I can implement the above proposal. Also, I'm not insistent on it, if you don't think it's a good idea.

**Comment by djmitche** [comment]
Indeed, we are at a very weird impasse!  However, let's defer to your system working and mine not.  The longer-term fix is to not build tc-tools anymore, and to instead build tc-web. And specifically for the tc-web build process to look like:
 * run `yarn` and `yarn build` in a container based on the node image
 * copy the resulting build/ directory into a new image based on the nginx image
..all with no Dockerfiles involved.  Once you finish that, this bug won't matter anymore!

If I have to, I can apply this patch manually in the interim.

**Comment by owlishDeveloper** [comment]
I've done my testing by building tc-web, not tools. That sounds like something to try tho!

**Comment by djmitche** [comment]
It'd be even weirder if stretch worked for tc-web and jessie worked for tc-tools.  Anyway, let's focus on not building a custom Dockerfile like this, rather than trying to get the custom Dockerfile to work.

**Pull request closed without merging**
